<?php
/**
 * @see Tritac_ChannelEngine_Block_Adminhtml_System_Config_Feed
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function makeRequest<?php echo $this->getId() ?>() {
        var elem = $('<?php echo $this->getId() ?>');
        var resultElem = $('<?php echo 'ce_res_'. $this->getId() ?>')
        var result = "<?php echo $this->__("Failed to run manual task. See magento log.") ?>";
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            onSuccess: function(response) {
                try {
                    response = response.responseText.evalJSON(true);
                    if (!response.error) {
                        elem.removeClassName('fail').addClassName('success')
                    } else {
                        elem.removeClassName('success').addClassName('fail')
                    }
                    result = response.message;
                } catch (e) {
                    elem.removeClassName('success').addClassName('fail')
                }
                resultElem.update(result);
            },
            onFailure: function(response) {
                elem.removeClassName('success').addClassName('fail');
                resultElem.update(result);
            }
        });
    }
    //]]>
</script>
<?php echo $this->getButtonHtml(); ?>
<span id="ce_res<?php echo $this->getId() ?>"><?php echo $this->escapeHtml($this->getLabel()) ?></span>
