<?php if($this->getAccountName()): ?>
    <script>
        (function (T, r, i, t, a, c) {
            T.ce = T.ce || function () { T.ce.eq = T.ce.eq || []; T.ce.eq.push(arguments); }, T.ce.url = t;
            a = r.createElement(i); a.async = 1; a.src = t + '/content/scripts/ce.js';
            c = r.getElementsByTagName(i)[0]; c.parentNode.insertBefore(a, c);
        })(window, document, 'script', '//www.channelengine.net');
         
        ce('set:account', '<?php echo($this->getAccountName()); ?>');
        ce('track:click');
    </script>
<?php endif ?>